import { formatDuration } from "@lare/shared";
import { Bot, CodeXml, Lightbulb, ListChecks, ThumbsUp, TriangleAlert } from "lucide-react";
import type { ReactNode } from "react";
import { cn } from "@/lib/cn";
import type { ReviewView } from "@/lib/parse";
import { cardClass } from "@/lib/styles";

function scoreTone(score: number): string {
  if (score >= 80) return "text-emerald-400";
  if (score >= 60) return "text-amber-400";
  return "text-rose-400";
}
function barTone(score: number): string {
  if (score >= 80) return "bg-emerald-400";
  if (score >= 60) return "bg-amber-400";
  return "bg-rose-400";
}

const KIND: Record<
  ReviewView["moments"][number]["kind"],
  { icon: typeof ThumbsUp; label: string; ring: string; text: string }
> = {
  good: {
    icon: ThumbsUp,
    label: "Good",
    ring: "border-emerald-500/40 bg-emerald-500/10",
    text: "text-emerald-400",
  },
  issue: {
    icon: TriangleAlert,
    label: "Issue",
    ring: "border-rose-500/40 bg-rose-500/10",
    text: "text-rose-400",
  },
  suggestion: {
    icon: Lightbulb,
    label: "Suggestion",
    ring: "border-amber-500/40 bg-amber-500/10",
    text: "text-amber-400",
  },
};

/** Stable, content-derived React keys; duplicates get a suffix instead of using array indices. */
function withKeys<T>(
  items: readonly T[],
  base: (item: T) => string,
): Array<{ key: string; item: T }> {
  const seen = new Map<string, number>();
  return items.map((item) => {
    const b = base(item);
    const n = seen.get(b) ?? 0;
    seen.set(b, n + 1);
    return { key: n === 0 ? b : `${b}#${n}`, item };
  });
}

export function InterviewReview({ review }: { review: ReviewView }) {
  const moments = withKeys(review.moments, (m) => `${m.t_ms}:${m.kind}:${m.source}`);
  const iterations = withKeys(review.code_iterations, (c) => `${c.t_ms}:${c.label}`);
  const steps = withKeys(review.next_steps, (s) => s);

  return (
    <section className={`${cardClass} p-4 sm:p-5`} aria-labelledby="ai-review-heading">
      <header className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h2
            id="ai-review-heading"
            className="flex items-center gap-2 text-lg font-semibold text-zinc-50"
          >
            <Bot className="size-5 text-amber-400" />
            AI interview review
          </h2>
          <p className="mt-1 text-xs text-zinc-500">
            Generated by {review.model} · {new Date(review.created_at).toLocaleDateString()}
          </p>
        </div>
        {review.overall !== null && (
          <div className="text-right">
            <div className={cn("text-4xl font-bold tabular-nums", scoreTone(review.overall))}>
              {review.overall}
              <span className="text-base font-medium text-zinc-500">/100</span>
            </div>
            <p className="text-xs uppercase tracking-wide text-zinc-500">Overall</p>
          </div>
        )}
      </header>

      {review.scores.length > 0 && (
        <dl className="mt-5 grid gap-3 sm:grid-cols-2">
          {review.scores.map((s) => (
            <div key={s.key} className="rounded-xl border border-zinc-800/80 bg-zinc-950/40 p-3">
              <div className="flex items-baseline justify-between">
                <dt className="text-sm font-medium text-zinc-200">{s.label}</dt>
                <dd className={cn("text-sm font-semibold tabular-nums", scoreTone(s.score))}>
                  {s.score}
                </dd>
              </div>
              <div className="mt-2 h-1.5 overflow-hidden rounded-full bg-zinc-800">
                <div
                  className={cn("h-full rounded-full", barTone(s.score))}
                  style={{ width: `${Math.max(0, Math.min(100, s.score))}%` }}
                />
              </div>
              <dd className="mt-2 text-xs leading-relaxed text-zinc-400">{s.rationale}</dd>
            </div>
          ))}
        </dl>
      )}

      {review.summary && (
        <p className="mt-5 text-sm leading-relaxed text-zinc-300">{review.summary}</p>
      )}

      {review.moments.length > 0 && (
        <SubSection title="Moments" icon={<TriangleAlert className="size-4 text-zinc-500" />}>
          <ol className="relative ml-2 space-y-4 border-l border-zinc-800 pl-5">
            {moments.map(({ key, item: m }) => {
              const kind = KIND[m.kind];
              const Icon = kind.icon;
              return (
                <li key={key} className="relative">
                  <span
                    className={cn(
                      "absolute -left-[29px] top-0.5 inline-flex size-4 items-center justify-center rounded-full border",
                      kind.ring,
                    )}
                  >
                    <Icon className={cn("size-2.5", kind.text)} />
                  </span>
                  <div className="flex flex-wrap items-center gap-2 text-xs">
                    <span className="rounded bg-zinc-800 px-1.5 py-0.5 font-mono text-zinc-300">
                      {formatDuration(m.t_ms)}
                    </span>
                    <span className={cn("font-semibold", kind.text)}>{kind.label}</span>
                    <span className="text-zinc-600">from {m.source}</span>
                  </div>
                  {m.quote && (
                    <blockquote className="mt-1.5 border-l-2 border-zinc-700 pl-3 text-sm italic text-zinc-400">
                      “{m.quote}”
                    </blockquote>
                  )}
                  <p className="mt-1.5 text-sm leading-relaxed text-zinc-300">{m.comment}</p>
                </li>
              );
            })}
          </ol>
        </SubSection>
      )}

      {review.code_iterations.length > 0 && (
        <SubSection title="Code iterations" icon={<CodeXml className="size-4 text-zinc-500" />}>
          <ol className="space-y-3">
            {iterations.map(({ key, item: c }) => (
              <li key={key} className="rounded-xl border border-zinc-800/80 bg-zinc-950/40 p-3">
                <div className="flex flex-wrap items-center gap-2 text-xs">
                  <span className="rounded bg-zinc-800 px-1.5 py-0.5 font-mono text-zinc-300">
                    {formatDuration(c.t_ms)}
                  </span>
                  <span className="text-sm font-medium text-zinc-100">{c.label}</span>
                  {c.complexity && (
                    <span className="rounded-full border border-zinc-700 px-2 py-0.5 font-mono text-[11px] text-zinc-300">
                      {c.complexity}
                    </span>
                  )}
                </div>
                <p className="mt-1.5 text-sm leading-relaxed text-zinc-400">{c.assessment}</p>
              </li>
            ))}
          </ol>
        </SubSection>
      )}

      {review.next_steps.length > 0 && (
        <SubSection title="Next steps" icon={<ListChecks className="size-4 text-zinc-500" />}>
          <ul className="space-y-2">
            {steps.map(({ key, item: step }) => (
              <li key={key} className="flex gap-2 text-sm text-zinc-300">
                <span className="mt-2 size-1.5 shrink-0 rounded-full bg-amber-400" />
                <span className="leading-relaxed">{step}</span>
              </li>
            ))}
          </ul>
        </SubSection>
      )}
    </section>
  );
}

function SubSection({
  title,
  icon,
  children,
}: {
  title: string;
  icon: ReactNode;
  children: ReactNode;
}) {
  return (
    <div className="mt-6">
      <h3 className="mb-3 flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-zinc-400">
        {icon}
        {title}
      </h3>
      {children}
    </div>
  );
}
