-- ---------------------------------------------------------------------------
-- Short, shareable post URLs
--
-- Post links were the raw primary key: /p/433b7577-e89a-4d65-b52b-947f1fb56105.
-- Every post now also carries an 11-character NanoID `slug`, so the same post is
-- /p/V1StGXR8Z5j.
--
-- The slug is generated by a column default rather than in the apps, because posts
-- are inserted from three places (the web app, the desktop app, and the edge
-- functions) and every one of them has to end up with a slug. The UUID `id` stays
-- the primary key and every foreign key keeps pointing at it — the slug is purely
-- the public handle, which also means old UUID links keep resolving (the web app
-- looks up either and redirects UUIDs to the canonical slug).
-- ---------------------------------------------------------------------------

-- NanoID's default alphabet and length. 64 symbols means each random byte maps onto
-- exactly one symbol with `& 63`, so there is no modulo bias to correct for.
create or replace function public.nanoid(size integer default 11)
returns text language plpgsql volatile as $$
declare
  alphabet constant text :=
    'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
  bytes bytea;
  result text := '';
  i integer;
begin
  if size < 1 then
    raise exception 'nanoid size must be positive, got %', size;
  end if;
  bytes := extensions.gen_random_bytes(size);
  for i in 0 .. size - 1 loop
    result := result || substr(alphabet, (get_byte(bytes, i) & 63) + 1, 1);
  end loop;
  return result;
end $$;

comment on function public.nanoid(integer) is
  'URL-safe random id using NanoID''s alphabet (A-Za-z0-9_-). Default length 11.';

alter table public.posts add column if not exists slug text;

-- Retry on the (vanishingly unlikely) unique collision instead of failing the insert.
-- Defined after the column exists so the `posts.slug` reference resolves.
create or replace function public.unique_post_slug()
returns text language plpgsql volatile as $$
declare
  candidate text;
  attempt integer := 0;
begin
  loop
    candidate := public.nanoid(11);
    exit when not exists (select 1 from public.posts where slug = candidate);
    attempt := attempt + 1;
    if attempt >= 10 then
      raise exception 'could not allocate a unique post slug after % attempts', attempt;
    end if;
  end loop;
  return candidate;
end $$;

-- Backfill existing rows before the not-null constraint goes on.
update public.posts set slug = public.unique_post_slug() where slug is null;

create unique index if not exists posts_slug_key on public.posts (slug);

alter table public.posts
  alter column slug set default public.unique_post_slug(),
  alter column slug set not null;

alter table public.posts drop constraint if exists posts_slug_format;
alter table public.posts
  add constraint posts_slug_format check (slug ~ '^[A-Za-z0-9_-]{11}$');
